### ISSUE TITLE
Issue: Section Skip Broken or Missing Logic

### ISSUE THREAD

**Issue by merddyin** [EvotecIT/PSWinDocumentation#13]
First, love what you've built here, particularly in the latest version with the ability to provide a config file for runtime. 

Issue:
You provide the option to bypass sections via $Document, however code still runs unless all related elements are also bypassed. 

Runtime Environment: 
Windows 10 v1803
PowerShell v5.1
Module Versions - Latest of all dependent modules, pulled directly from GitHub

Expectation:
Setting non-primary items without sub-dependencies as $false for inclusion should result in those portions of the data gathering process to be bypassed unless they are a dependency for another item.

Example:
I set 'SectionDomainOrganizationalUnits' to $true and 'SectionExcelDomainOrganizationalUnitsBasicACL' and 'SectionExcelDomainOrganizationalUnitsExtended' to $false with the expectation that the basic OU information would be collected, but the ACLs would not. Based on what I interpret from the script logic, selecting one will always include all. I can see why you need to get the base org units to support permissions, however there is no reason to require permissions when all I want is a list of org units.

It would be great if:
a) the $documents schema were arranged to more clearly show dependency relationships, possibly by making child dependencies sub-sections within the config (ie SectionDomainOrganizationalUnits for parent and SectionDomainOrganizationalUnits.SubSectionBaseACL and SubSectionExtACL for depedencies) 
b) when setting a parent item to $false, but setting a child dependent item to $true, prompt the user to tell them of the dependency and ask if they want to go ahead and collect the required parent, or skip the child item
c) Alternative: code to collect a reduced set of values or data when excluding the parent, but including a child (ie Including SectionExcelDomainUsersNeverExpiring should retrieve only the minimum required attributes rather than always getting all users with all properties, which causes performance problems *see other issue*)

**Comment by PrzemyslawKlys** [comment]
Thank you. I do see good points in here and I tried excluding some code from running if there is no output needed. For some stuff, it's working, for some stuff I was too lazy to type it out. I am testing with fairly small domain so it wasn't big deal for me but I've been hitting more and more issues with larger domains so I agree that something has to be done to prevent code from running.

Probably writing down all relationships between each other is a good starting point.  

There are probably some mistakes in code logic due to a large number of things that touch each other. So I need to go thru all those and fix it. 

As for performance and all users, I'll touch the other issue. But since I had similar bad perf issues and export problems on 6k+ users I was considering to limit it, or even give users a choice what fields they want.

**Comment by PrzemyslawKlys** [comment]
Addressed in: https://github.com/EvotecIT/PSWinDocumentation.AD - still, performance requires work. 
Description of why/how to: https://evotec.xyz/what-do-we-say-to-writing-active-directory-documentation/
