### ISSUE TITLE
Get-WinO365Exchange issue

### ISSUE THREAD

**Issue by Ginshen** [EvotecIT/PSWinDocumentation#19]
Good Evening,

Attempting to run your scripts for an O365 tenant and had to fix several things initially using the examples provided etc.  However, stuck here:

`Get-WinO365Exchange : The term 'Get-WinO365Exchange' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Program Files\WindowsPowerShell\Modules\PSWinDocumentation\0.5.0\PSWinDocumentation.ps1:107 char:55
+ ...     'ExchangeOnline' { $DataInformation = Get-WinO365Exchange -TypesR ...
+                                               ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-WinO365Exchange:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

Any help you can provide?

**Comment by PrzemyslawKlys** [comment]
Well, I do need to udpate `PSWinDocumentation` to changes I am doing. Some time ago I've decided to split `PSWinDocumentation` into submodules because `PSWinDocumentation`, as is, is very stiff. `O365` was never ready for production thou.

You should take a look at: 

- PSWinDocumentation.AD - https://github.com/EvotecIT/PSWinDocumentation.AD - with the described process in here https://evotec.xyz/what-do-we-say-to-writing-active-directory-documentation/ - it's for AD but the same road for O365 is in progress for O365. 

- PSWinDocumentation.O365 - https://github.com/EvotecIT/PSWinDocumentation.O365 

While I work on O365 and AD, the main, stiff module is not really touched therefore some things may not work correctly. I say stiff because you're limited with output and you can't really create nice docs with some external stuff from other systems. 

In examples, you have a small how to use it. It's a work in progress thou. There are lots of data sets that are somewhat ok, but the only a subset of them was put into Dashimo or Documentimo for now. You also have to do your own connection to O365. I'm using my own Connectimo module but feel free to use anything. You need to be connected for the module to work properly as it touches Teams, Skype, Exchange, MSOL, Azure so you need to connect to 5 of them for the module to not bug out (I will, later on, try to make sure error handling for not connected modules is much better but for now it is what it is).

**Comment by PrzemyslawKlys** [comment]
I've updated the main module so it won't error out like that. I've updated examples as well. It's the basically the same approach as per https://github.com/EvotecIT/PSWinDocumentation/issues/20

**Comment by PrzemyslawKlys** [comment]
Closing this, as the issue should be solved. However, improvements to O365 as such are not yet over.
